[package]
name = "torda-mod-procmon"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "torda_mod_procmon"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio = { workspace = true }
torda-core = { path = "../../core" }
torda-ocsf = { path = "../../ocsf" }

[dev-dependencies]
torda-substrate = { path = "../../substrate" }
